version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "3030:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/avaliacao_mba_rails
      REDIS_URL: redis://redis:6379/1
    working_dir: /workspace
    command: ["./entrypoint.sh", "sleep", "infinity"]
    user: "1000:1000"

  sidekiq:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/avaliacao_mba_rails
      REDIS_URL: redis://redis:6379/1
    working_dir: /workspace
    command: ["./entrypoint.sh", "bundle", "exec", "sidekiq"]
    user: "1000:1000"

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres_data:
